[
{
    "model": "trigger_app.telescopeprojectid",
    "pk": 1,
    "fields": {
        "id": "T001",
        "password": "TestingOnly",
        "description": "Testing MWA",
        "telescope": "MWA_VCS",
    }
},
{
    "model": "trigger_app.proposalsettings",
    "pk": 1,
    "fields": {
        "telescope": "MWA_VCS",
        "project_id": "T001",
        "proposal_id": "TEST",
        "proposal_description": "Testing MWA",
        "event_telescope": null,
        "trig_min_duration": 0.256,
        "trig_max_duration": 1.024,
        "pending_min_duration_1": 1.025,
        "pending_max_duration_1": 2.056,
        "pending_min_duration_2": 0.128,
        "pending_max_duration_2": 0.255,
        "fermi_prob": 50.0,
        "swift_rate_signf": 0.0,
        "repointing_limit": 10.0,
        "mwa_horizon_limit": 10.0,
        "testing": true,
        "source_type": "GRB",
        "mwa_freqspecs": "121,24",
        "mwa_nobs": 1,
        "mwa_exptime": 800,
        "mwa_calexptime": 300.0,
        "mwa_freqres": 40.0,
        "mwa_inttime": 0.5,
    }
},
]